# docker-compose.yml
services:
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/e-commerce/static
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: ./e-commerce
    volumes:
      - ./e-commerce:/e-commerce
      - static_volume:/e-commerce/static
      - media_volume:/e-commerce/media
    env_file:
      - .env-prod
    expose:
      - 8000:8000
    depends_on:
      - mongo
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000

  mongo:
    image: mongo:6.0
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017


volumes:
    static_volume:
    media_volume:
